# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload app to App Store Connect"
  lane :release do |options|
    upload_to_app_store(
      ipa: options[:ipa_path],
      api_key: {
        key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_content: ENV['APP_STORE_CONNECT_PRIVATE_KEY'],
        is_key_content_base64: true,
        duration: 1200
      },
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      force: true
    )
  end
end