name: Upload to TestFlight

on:
  workflow_dispatch:

jobs:
  upload_to_testflight:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode App Store Connect API Key (.p8)
        run: |
          echo "$APP_STORE_CONNECT_API_KEY_P8_BASE64" | base64 --decode > AuthKey.p8
        env:
          APP_STORE_CONNECT_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

      - name: Find .ipa file
        id: find_ipa
        run: |
          IPA_PATH=$(find . -type f -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "IPA not found!"
            exit 1
          fi
          echo "Found IPA at: $IPA_PATH"
          echo "ipa_path=$IPA_PATH" >> $GITHUB_OUTPUT

      - name: Upload App to TestFlight using Fastlane
        run: |
          IPA_PATH="${{ steps.find_ipa.outputs.ipa_path }}"
          if [ -z "$IPA_PATH" ]; then
            echo "Error: IPA path is empty."
            exit 1
          fi
          echo "Uploading $IPA_PATH to TestFlight..."
          bundle exec fastlane pilot upload --ipa "$IPA_PATH" --api_key_path "./AuthKey.p8"
