name: Build Project
on:
  workflow_call:

jobs:
  build-project:
    runs-on: self-hosted
    steps:
      - name: Build project (disable code signing)
        run: |
          xcodebuild clean build \
          -scheme WfmUser \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO | xcpretty
