name: Checkout Repository
on:
  workflow_call:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean workspace completely
        run: |
          echo "Stopping any git processes..."
          pkill -f git || true
          cd /Users/birol/actions-runner/_work/WfmUser-iOS/
          rm -rf WfmUser-iOS || true
          mkdir -p WfmUser-iOS

      - name: Manual git clone with token
        run: |
          REPO_URL="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git clone "$REPO_URL" WfmUser-iOS
          cd WfmUser-iOS
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            git checkout ${{ github.sha }}
          fi

      - name: Verify checkout
        run: |
          echo "Working directory: $(pwd)"
          git status
          git remote -v
          git log --oneline -n 3
