name: Codacy Analysis
on:
  workflow_call:

jobs:
  codacy-analysis:
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug token availability
        run: |
          echo "Checking token availability..."
          if [ -n "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
            echo "✅ CODACY_PROJECT_TOKEN is set"
            echo "Token length: ${#CODACY_PROJECT_TOKEN}"
          else
            echo "❌ CODACY_PROJECT_TOKEN is empty or not set"
            exit 1
          fi
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        
      - name: Verify wget installation
        run: |
          which wget
          wget --version

        # Codacy analiz
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          max-allowed-issues: 1500
          upload: true
          run-docker-tools: true
