name: Create Tag
on:
  workflow_call:

jobs:
  create-tag:
    runs-on: self-hosted
    steps:
     - name: Create Git Tag
       env:
        TAG_NAME: "release${{ env.FOLDER_NAME }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
        git tag "$TAG_NAME"
    
        # GITHUB_TOKEN ile push işlemi için authentication ayarı
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
    
        git push origin "$TAG_NAME"
