name: Generate Documentation
on:
  workflow_call:

jobs:
  docs:
    runs-on: self-hosted
    steps:
      - name: Generate Documentation with Jazzy
        run: |
          # Homebrew Ruby varsa onu kullan, yoksa sistem Ruby
          if command -v /opt/homebrew/opt/ruby/bin/ruby &> /dev/null; then
            echo "Using Homebrew Ruby for Jazzy"
            /opt/homebrew/lib/ruby/gems/3.0.0/bin/jazzy \
              --clean \
              --min-acl internal \
              --module "WfmUser" \
              --build-tool-arguments -project,WfmUser.xcodeproj,-scheme,WfmUser,-sdk,iphonesimulator \
              --output docs
          else
            echo "Using system Ruby for Jazzy"
            jazzy \
              --clean \
              --min-acl internal \
              --module "WfmUser" \
              --build-tool-arguments -project,WfmUser.xcodeproj,-scheme,WfmUser,-sdk,iphonesimulator \
              --output docs
          fi
