name: Build WfmUser App

on:
  push:
    branches:
      - '**'  # tüm branchler
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml

  setup-xcode:
    uses: ./.github/workflows/xcode-setup.yml
    needs: checkout

  setup-here-sdk:
    uses: ./.github/workflows/here-sdk-setup.yml
    needs: setup-xcode

  # build-project:
  #  uses: ./.github/workflows/build-project.yml
  #  needs: setup-here-sdk

  unit-tests:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/unit-tests.yml
    needs: setup-here-sdk

  docs:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/generate-docs.yml
    needs: setup-here-sdk

  codacy:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/codacy-analysis.yml
    needs: unit-tests

  upload:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/upload-to-drive.yml
    needs: codacy

  generate-changelog:
    # if: github.event_name == 'pull_request' && github.base_ref == 'main'
    uses: ./.github/workflows/generate-changelog.yml
    needs: setup-here-sdk

 # tags:
 #   uses: ./.github/workflows/create-tag.yml
 #   needs: checkout
