name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g. release-v1)'
        required: true

jobs:
  create_tag:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
