name: Run Unit Tests
on:
  workflow_call:
jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: |
            build/Build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/*.xcodeproj', '**/*.swift', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-
      
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
        if: hashFiles('**/Podfile.lock') != ''
      
      - name: Install CocoaPods
        run: pod install --repo-update
        if: hashFiles('**/Podfile.lock') != ''
      
      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project WfmUser.xcodeproj \
            -scheme WfmUser \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
            -derivedDataPath build \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
            -test-timeouts-enabled YES \
            -maximum-test-execution-time-allowance 300 \
            -only-testing:WfmUserTests \
            | tee xcodebuild_test.log | xcpretty --color --report junit
