name: Run Unit Tests
on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Run Unit Tests (no build)
        run: |
          xcodebuild test-without-building \
            -scheme WfmUser \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
            -derivedDataPath build \
            | tee xcodebuild_test.log | xcpretty
